using System;

namespace Reviewer2.Data.Models;

/// <summary>
/// Represents a file uploaded in association with a paper submission.
/// </summary>
/// <remarks>
/// <para>
/// The file contents themselves are stored in external storage
/// (e.g., local file system or cloud storage). This entity stores only
/// the metadata required for retrieval, auditing, and workflow validation.
/// </para>
/// <para>
/// Instances of <see cref="PaperFile"/> are domain-safe and enforce
/// invariants at construction time to prevent invalid states.
/// </para>
/// </remarks>
public class PaperFile
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PaperFile"/> class.
    /// Required by Entity Framework for materialization.
    /// </summary>
    private PaperFile() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="PaperFile"/> class
    /// with validated metadata.
    /// </summary>
    /// <param name="paperId">The identifier of the associated paper.</param>
    /// <param name="type">The type and purpose of the uploaded file.</param>
    /// <param name="storagePath">
    /// The storage-relative path used by the file storage system.
    /// </param>
    /// <param name="originalFileName">
    /// The original file name provided by the user.
    /// </param>
    /// <param name="sizeInBytes">The size of the file in bytes.</param>
    /// <exception cref="ArgumentException">
    /// Thrown when any argument violates domain invariants.
    /// </exception>
    public PaperFile(
        Guid paperId,
        FileType type,
        string storagePath,
        string originalFileName,
        long sizeInBytes)
    {
        if (paperId == Guid.Empty)
            throw new ArgumentException("PaperId cannot be empty.", nameof(paperId));

        if (!Enum.IsDefined(typeof(FileType), type))
            throw new ArgumentException("Invalid file type.", nameof(type));

        if (string.IsNullOrWhiteSpace(storagePath))
            throw new ArgumentException("Storage path is required.", nameof(storagePath));

        if (string.IsNullOrWhiteSpace(originalFileName))
            throw new ArgumentException("Original file name is required.", nameof(originalFileName));

        if (sizeInBytes <= 0)
            throw new ArgumentException("File size must be positive.", nameof(sizeInBytes));

        Id = Guid.NewGuid();
        PaperId = paperId;
        Type = type;
        StoragePath = storagePath;
        OriginalFileName = originalFileName;
        SizeInBytes = sizeInBytes;
        UploadedAtUtc = DateTime.UtcNow;
    }

    /// <summary>
    /// Gets the unique identifier for this file record.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Gets the identifier of the paper this file belongs to.
    /// </summary>
    public Guid PaperId { get; private set; }

    /// <summary>
    /// Gets the purpose or category of the uploaded file.
    /// </summary>
    public FileType Type { get; private set; }

    /// <summary>
    /// Gets the storage-relative path used by the file storage system
    /// to locate the file contents.
    /// </summary>
    /// <remarks>
    /// This value is generated by the file storage service and should
    /// not be exposed directly to end users.
    /// </remarks>
    public string StoragePath { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the original file name as provided by the user at upload time.
    /// </summary>
    /// <remarks>
    /// This value may be displayed to users when downloading the file.
    /// </remarks>
    public string OriginalFileName { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the size of the file in bytes at the time of upload.
    /// </summary>
    public long SizeInBytes { get; private set; }

    /// <summary>
    /// Gets the date and time (UTC) when the file was uploaded.
    /// </summary>
    public DateTime UploadedAtUtc { get; private set; }
}

/// <summary>
/// Defines the type and purpose of a file uploaded for a paper submission.
/// </summary>
/// <remarks>
/// The file type determines when the file is required in the workflow
/// and who may access it.
/// </remarks>
public enum FileType
{
    /// <summary>
    /// The initial full paper submission provided for review.
    /// This version is typically visible to reviewers.
    /// </summary>
    InitialSubmission = 0,

    /// <summary>
    /// The final camera-ready version submitted after acceptance.
    /// This version is typically used for proceedings publication.
    /// </summary>
    CameraReady = 1,

    /// <summary>
    /// The signed copyright or licensing agreement required
    /// prior to publication.
    /// </summary>
    CopyrightForm = 2
}
