version: "3.9"

services:
  app:
    build: .
    container_name: reviewer2-app
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Reviewer2Connection: ${REVIEWER2_CONNECTION}